# Generated by Django 2.2.3 on 2019-10-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completo',
            field=models.BooleanField(default=False, verbose_name='Completo'),
        ),
    ]
