# Generated by Django 2.2.7 on 2019-11-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_controle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='plano',
            field=models.IntegerField(choices=[(0, 'Gratuito'), (1, 'Premium')], default=0, max_length=1, verbose_name='Plano'),
        ),
    ]
