# Generated by Django 2.2.7 on 2019-11-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191117_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='plano',
            field=models.IntegerField(choices=[(0, 'Gratuito'), (1, 'Premium')], default=0, verbose_name='Plano'),
        ),
    ]
