# Generated by Django 2.2.3 on 2019-10-28 23:45

import cos.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50, verbose_name='Nome')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.Empresa', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('codigo', models.CharField(default=cos.models.gerar_os_cod, max_length=14, primary_key=True, serialize=False, verbose_name='Código')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[(0, 'Orçamento'), (1, 'Liberado para manutenção'), (2, 'Em manutenção'), (3, 'Aguardando pagamento'), (4, 'Finalizado'), (9, 'Cancelado')], default=0, max_length=1, verbose_name='Status')),
                ('previsao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Previsão Entrega')),
                ('modelo', models.CharField(max_length=40, verbose_name='Modelo')),
                ('identificacao', models.CharField(blank=True, max_length=40, null=True, verbose_name='Identificação')),
                ('q_molhou', models.BooleanField(blank=True, default=0, max_length=1, null=True, verbose_name='O dispositivo molhou?')),
                ('q_liga', models.BooleanField(blank=True, default=0, max_length=1, null=True, verbose_name='O dispositivo liga?')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.Colaborador', verbose_name='Colaborador')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.Cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.Empresa', verbose_name='Empresa')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cos.Marca', verbose_name='Marca')),
            ],
        ),
    ]
