# Generated by Django 2.2.7 on 2019-11-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0004_auto_20191117_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Orçamento'), (1, 'Liberado para manutenção'), (2, 'Em manutenção'), (3, 'Aguardando pagamento'), (4, 'Finalizado'), (9, 'Cancelado')], default=0, max_length=1, verbose_name='Status'),
        ),
    ]
