# Generated by Django 2.2.7 on 2019-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='dono',
            field=models.CharField(max_length=40, verbose_name='Dono'),
        ),
    ]
