# Generated by Django 2.2.3 on 2019-10-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='E-mail'),
        ),
    ]
