# Generated by Django 2.2.7 on 2019-11-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20191111_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vinculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa', verbose_name='Vinculado a'),
        ),
    ]
