# Generated by Django 2.2.7 on 2019-11-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_cliente_vinculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpresaSelecionada',
        ),
    ]
