# Generated by Django 2.2.7 on 2019-11-17 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_delete_empresaselecionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa', verbose_name='Empresa'),
        ),
    ]
