# Generated by Django 2.2.7 on 2019-11-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20191124_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome_unico',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Nome único'),
        ),
    ]
